"""Three backtests generated by the 2026-07-02 session. SPY 5m, 10 years.

A. VWAP magnet: does (VWAP - price) at 15:00 predict last-hour drift?
B. Up-walk symmetry: 3+ closes above SMA9 with %B>0.65 -- persistence/payoff
   vs the down-walk, and what follows the walk's end.
C. Down-walk confirmation + 30m alignment, scored in scalper units:
   P(additional drop >= 0.15% / 0.25% before the walk ends).
"""
import math
import os
from datetime import time as dtime
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd

OUT = os.path.dirname(os.path.abspath(__file__))
NY = ZoneInfo("America/New_York")

df = pd.read_csv(os.path.join(OUT, "SPY_5m_full.csv"))
df["ts"] = pd.to_datetime(df["timestamps"]).dt.tz_convert(NY)
df = df.sort_values("ts").reset_index(drop=True)
d5 = df[(df["ts"].dt.time >= dtime(9, 30)) & (df["ts"].dt.time <= dtime(15, 55))].reset_index(drop=True)
c = d5["close"]
d5["sma9"] = c.rolling(9).mean()
mid = c.rolling(20).mean()
sd = c.rolling(20).std()
d5["pctb"] = (c - (mid - 2 * sd)) / (4 * sd)
d5["day"] = d5["ts"].dt.date
pv = d5["vwap"] * d5["volume"]
d5["svwap"] = pv.groupby(d5["day"]).cumsum() / d5["volume"].groupby(d5["day"]).cumsum()
e12 = c.ewm(span=12, adjust=False).mean()
e26 = c.ewm(span=26, adjust=False).mean()
m = e12 - e26
d5["hist"] = m - m.ewm(span=9, adjust=False).mean()   # 5m hist (30m state via agg below)

# 30m hist for alignment
def agg30():
    minutes = (d5["ts"].dt.hour * 60 + d5["ts"].dt.minute) - 570
    grp = np.minimum(minutes // 30, 12)
    key = d5["day"].astype(str) + "_" + grp.astype(str)
    g = d5.groupby(key, sort=False)
    a = pd.DataFrame({"ts": g["ts"].first(), "close": g["close"].last(),
                      "end": g["ts"].last() + pd.Timedelta(minutes=5)})
    a = a.reset_index(drop=True).sort_values("ts").reset_index(drop=True)
    ee12 = a["close"].ewm(span=12, adjust=False).mean()
    ee26 = a["close"].ewm(span=26, adjust=False).mean()
    mm = ee12 - ee26
    a["hist"] = mm - mm.ewm(span=9, adjust=False).mean()
    return a

a30 = agg30()
ends30 = a30["end"].values
h30 = a30["hist"].values

o = d5["open"].values
h_ = d5["high"].values
l_ = d5["low"].values
cl = d5["close"].values
sma9 = d5["sma9"].values
pctb = d5["pctb"].values
vw = d5["svwap"].values
day = d5["day"].values
tod = (d5["ts"].dt.hour * 60 + d5["ts"].dt.minute).values
ts = d5["ts"].values
n = len(d5)
WARM = np.datetime64("2016-06-01")

day_rows = {}
for i, dy in enumerate(day):
    day_rows.setdefault(dy, []).append(i)
days = [dy for dy in day_rows if np.datetime64(pd.Timestamp(dy)) >= WARM and len(day_rows[dy]) >= 70]

# ---------------- A. VWAP magnet ----------------
print("=== A. VWAP magnet: state at 15:00 -> last-hour behavior ===")
buckets = [(-9, -0.004), (-0.004, -0.0015), (-0.0015, 0.0015), (0.0015, 0.004), (0.004, 9)]
labels = ["price >0.4% ABOVE vwap", "0.15-0.4% above", "within 0.15%", "0.15-0.4% below", "price >0.4% BELOW vwap"]
rows_by_bucket = {k: [] for k in range(5)}
close_to_vwap = []
for dy in days:
    rows = day_rows[dy]
    i15 = next((i for i in rows if tod[i] >= 15 * 60), None)
    if i15 is None:
        continue
    p15 = cl[i15]
    v15 = vw[i15]
    gap = (v15 - p15) / p15          # positive = vwap above price
    eod = rows[-1]
    r_last = cl[eod] / p15 - 1
    toward = np.sign(r_last) == np.sign(gap) and gap != 0
    frac = r_last / gap if abs(gap) > 0.0015 else np.nan
    for k, (a, b) in enumerate(buckets):
        if a <= -gap < b:            # -gap = price-above-vwap measure
            rows_by_bucket[k].append((r_last, toward, frac))
            break
    close_to_vwap.append(abs(cl[eod] / vw[eod] - 1))
for k, lbl in enumerate(labels):
    arr = rows_by_bucket[k]
    if not arr:
        continue
    r = np.array([x[0] for x in arr])
    tw = np.array([x[1] for x in arr])
    fr = np.array([x[2] for x in arr], dtype=float)
    frv = fr[~np.isnan(fr)]
    print(f"  {lbl:<24s} n={len(r):>4d}  last-hr avg={r.mean():>+8.3%}  P(move toward vwap)={tw.mean():>6.1%}"
          + (f"  med frac of gap closed={np.median(frv):>6.1%}" if len(frv) > 20 else ""))
ctv = np.array(close_to_vwap)
print(f"  context: P(close within 0.10% of final VWAP) any day = {(ctv <= 0.001).mean():.1%}; "
      f"median close-to-VWAP distance = {np.median(ctv):.3%}")

# ---------------- B. up-walk symmetry ----------------
above = (cl > sma9) & (pctb > 0.65)
below = (cl < sma9) & (pctb < 0.35)

def find_walks(mask, exit_cmp):
    walks = []
    i = 2
    while i < n - 1:
        if ts[i] < WARM or math.isnan(sma9[i]):
            i += 1
            continue
        if mask[i] and mask[i - 1] and mask[i - 2] and day[i] == day[i - 2]:
            s = i - 2
            de = day_rows[day[s]][-1]
            j = i
            while j + 1 <= de and not exit_cmp(j + 1):
                j += 1
            if j - s + 1 >= 5:
                walks.append((s, min(j + 1, de), de))
            i = j + 2
        else:
            i += 1
    return walks

up_walks = find_walks(above, lambda k: cl[k] < sma9[k])
dn_walks = find_walks(below, lambda k: cl[k] > sma9[k])
print("\n=== B. up-walk (SMA9/upper band) vs down-walk symmetry ===")
for name, walks, sgn in [("UP-walks", up_walks, +1), ("DOWN-walks", dn_walks, -1)]:
    lens = np.array([e - s for s, e, _ in walks])
    drift = np.array([sgn * (cl[e] / cl[s] - 1) for s, e, _ in walks])
    after30 = []
    for s, e, de in walks:
        if e + 6 < n and day[e + 6] == day[e]:
            after30.append(sgn * (cl[e + 6] / cl[e] - 1))
    a30_ = np.array(after30)
    print(f"  {name:<11s} n={len(walks):>5d}  med len={np.median(lens):>3.0f} bars  "
          f"drift(favorable)={drift.mean():>+8.3%}  after-end 30m (same dir)={a30_.mean():>+8.3%} "
          f"P(cont)={ (a30_>0).mean():.1%}")

# ---------------- C. down-walk confirm + 30m alignment, scalper units ----------------
print("\n=== C. down-walk confirmation +-30m alignment: P(more drop before walk ends) ===")
def aligned_30m(t):
    k = np.searchsorted(ends30, t, side="right") - 1
    if k < 1:
        return False
    return h30[k] < h30[k - 1]      # 30m momentum still falling = aligned down

groups = {"30m aligned (hist falling)": [], "30m not aligned": []}
for s, e, de in dn_walks:
    conf = s + 2                     # confirmation bar (3rd below close)
    entry = cl[conf]
    lowest_after = l_[conf + 1:e + 1].min() if conf + 1 <= e else entry
    mfe = entry / lowest_after - 1   # favorable-for-short move before walk end
    drift_end = entry / cl[e] - 1
    key = "30m aligned (hist falling)" if aligned_30m(ts[conf] + np.timedelta64(5, "m")) else "30m not aligned"
    groups[key].append((mfe, drift_end))
for k, arr in groups.items():
    a = np.array(arr)
    print(f"  {k:<28s} n={len(a):>5d}  P(drop>=0.15%)={(a[:,0]>=0.0015).mean():>6.1%}  "
          f"P(drop>=0.25%)={(a[:,0]>=0.0025).mean():>6.1%}  avg drift to walk end={a[:,1].mean():>+8.3%}")
